/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SIgame;

import SIgame.view.*;
import SIgame.model.*;
import SIgame.controller.*;

public class App 
{
    public static void main(String[] args) 
    { 
        Score score = new Score();
        GameController controller = new GameController(score);
    }
}
