/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SIgame;

import SIgame.view.*;
import SIgame.model.*;
import SIgame.controller.*;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class App 
{
    public static void main(String[] args) 
    {
        TitleScreen titleScreen = new TitleScreen();
        titleScreen.drawMainMenu();
        ScoreModel score = new ScoreModel();
        TankModel tankModel = new TankModel(290, 420, 10);
        if (titleScreen.getDifficulty() != null)
        {
        if (titleScreen.getDifficulty().equals("Normal"))
        {
            GameController gameController = new GameController(score, "Normal");
            TankView tankView = gameController.getSpaceGUI().getTankView();
            TankController tankController = new TankController(tankModel, tankView, gameController);
            gameController.setTankView(tankView);
    
            Timer laserTimer = new Timer(15, new ActionListener() 
            {
                @Override
                public void actionPerformed(ActionEvent e) 
                {
                    gameController.moveLasers();
                    gameController.checkForCollisions();
                }
            });
            laserTimer.start();
        }
        else if (titleScreen.getDifficulty().equals("Hard"))
        {
            GameController gameController = new GameController(score, "Hard");
            TankView tankView = gameController.getSpaceGUI().getTankView();
            TankController tankController = new TankController(tankModel, tankView, gameController);
            gameController.setTankView(tankView);
    
            Timer laserTimer = new Timer(15, new ActionListener() 
            {
                @Override
                public void actionPerformed(ActionEvent e) 
                {
                    gameController.moveLasers();
                    gameController.checkForCollisions();
                }
            });
            laserTimer.start();
        }
        }
    }
}
